from setuptools import setup

setup(
    name='LemonamigaEbayScript',
    version='0.1',
    packages=['venv.lib.python3.7.site-packages.idna', 'venv.lib.python3.7.site-packages.lxml',
              'venv.lib.python3.7.site-packages.lxml.html', 'venv.lib.python3.7.site-packages.lxml.includes',
              'venv.lib.python3.7.site-packages.lxml.isoschematron', 'venv.lib.python3.7.site-packages.isort',
              'venv.lib.python3.7.site-packages.mysql', 'venv.lib.python3.7.site-packages.mysql.connector',
              'venv.lib.python3.7.site-packages.mysql.connector.django',
              'venv.lib.python3.7.site-packages.mysql.connector.fabric',
              'venv.lib.python3.7.site-packages.mysql.connector.locales',
              'venv.lib.python3.7.site-packages.mysql.connector.locales.eng', 'venv.lib.python3.7.site-packages.tests',
              'venv.lib.python3.7.site-packages.wrapt', 'venv.lib.python3.7.site-packages.pylint',
              'venv.lib.python3.7.site-packages.pylint.test.data', 'venv.lib.python3.7.site-packages.pylint.test.input',
              'venv.lib.python3.7.site-packages.pylint.test.input.func_w0401_package',
              'venv.lib.python3.7.site-packages.pylint.test.extensions',
              'venv.lib.python3.7.site-packages.pylint.test.functional',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.dummy',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.absimp',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.package',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.package.subpackage',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.beyond_top',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.bad_package',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.package_all',
              'venv.lib.python3.7.site-packages.pylint.test.regrtest_data.init_wildcard',
              'venv.lib.python3.7.site-packages.pylint.checkers', 'venv.lib.python3.7.site-packages.pylint.pyreverse',
              'venv.lib.python3.7.site-packages.pylint.reporters',
              'venv.lib.python3.7.site-packages.pylint.reporters.ureports',
              'venv.lib.python3.7.site-packages.pylint.extensions', 'venv.lib.python3.7.site-packages.MySQLdb',
              'venv.lib.python3.7.site-packages.MySQLdb.constants', 'venv.lib.python3.7.site-packages.astroid',
              'venv.lib.python3.7.site-packages.astroid.interpreter',
              'venv.lib.python3.7.site-packages.astroid.interpreter._import',
              'venv.lib.python3.7.site-packages.certifi', 'venv.lib.python3.7.site-packages.chardet',
              'venv.lib.python3.7.site-packages.chardet.cli', 'venv.lib.python3.7.site-packages.ebaysdk',
              'venv.lib.python3.7.site-packages.ebaysdk.soa', 'venv.lib.python3.7.site-packages.ebaysdk.http',
              'venv.lib.python3.7.site-packages.ebaysdk.poller', 'venv.lib.python3.7.site-packages.ebaysdk.finding',
              'venv.lib.python3.7.site-packages.ebaysdk.trading', 'venv.lib.python3.7.site-packages.ebaysdk.policies',
              'venv.lib.python3.7.site-packages.ebaysdk.shopping',
              'venv.lib.python3.7.site-packages.ebaysdk.merchandising',
              'venv.lib.python3.7.site-packages.ebaysdk.inventorymanagement',
              'venv.lib.python3.7.site-packages.samples', 'venv.lib.python3.7.site-packages.urllib3',
              'venv.lib.python3.7.site-packages.urllib3.util', 'venv.lib.python3.7.site-packages.urllib3.contrib',
              'venv.lib.python3.7.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.urllib3.packages',
              'venv.lib.python3.7.site-packages.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.requests', 'venv.lib.python3.7.site-packages.lazy_object_proxy',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='erik',
    author_email='',
    description='', install_requires=['ebaysdk', 'mysql']
)
